brew "git-delta"
brew "tmux"
brew "neovim"
brew "yazi"
brew "fd"
brew "ripgrep"
cask "font-jetbrains-mono-nerd-font"
cask "alacritty"
brew "fzf"
cask "karabiner-elements"
brew "k9s"
cask "docker"
cask "scroll-reverser"
cask "homerow"

brew "nvm"
brew "uv"

tap "jesseduffield/lazygit" 
brew "lazygit"
brew "lazydocker"

cask "google-chrome"
cask "obsidian"
cask "spotify"
cask "raycast"
cask "microsoft-word"
cask "messenger"
cask "bitwarden"
cask "discord"
cask "dropbox"
cask "google-drive"
cask "thunderbird"

cask "shottr"
cask "bluesnooze"

